// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/00       [399360]
Creator        : jbhyun
Date           : Tue Jun  8 15:56:04 2021
Host           : Linux root-ubuntu-2004-1 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jbhyun/Forge/BDTTrain/tmva
Training events: 38314
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "40" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "9" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 81
Nj                            Nj                            Nj                            Nj                                                              'I'    [3,12]
Nb                            Nb                            Nb                            Nb                                                              'I'    [1,5]
Ptl1                          Ptl1                          Ptl1                          Ptl1                                                            'F'    [20.0038032532,3528.63354492]
Ptl2                          Ptl2                          Ptl2                          Ptl2                                                            'F'    [10.0008687973,180.782180786]
Ptj1                          Ptj1                          Ptj1                          Ptj1                                                            'F'    [26.307554245,1258.36206055]
Ptj2                          Ptj2                          Ptj2                          Ptj2                                                            'F'    [25.1116371155,736.982543945]
Ptj3                          Ptj3                          Ptj3                          Ptj3                                                            'F'    [25.0010318756,522.453979492]
Ptb1                          Ptb1                          Ptb1                          Ptb1                                                            'F'    [25.0105686188,1143.94543457]
dEtall                        dEtall                        dEtall                        dEtall                                                          'F'    [3.77297401428e-05,4.61115884781]
dRll                          dRll                          dRll                          dRll                                                            'F'    [0.0932734832168,5.40484428406]
dRjj12                        dRjj12                        dRjj12                        dRjj12                                                          'F'    [0.394186288118,5.51146507263]
dRjj23                        dRjj23                        dRjj23                        dRjj23                                                          'F'    [0.401400059462,5.38182353973]
dRjj13                        dRjj13                        dRjj13                        dRjj13                                                          'F'    [0.407925158739,5.51293802261]
dRlj11                        dRlj11                        dRlj11                        dRlj11                                                          'F'    [0.400195807219,5.56941890717]
dRlj12                        dRlj12                        dRlj12                        dRlj12                                                          'F'    [0.400101214647,5.62248182297]
dRlj13                        dRlj13                        dRlj13                        dRlj13                                                          'F'    [0.400550603867,5.40495634079]
dRlj21                        dRlj21                        dRlj21                        dRlj21                                                          'F'    [0.400000184774,5.42530488968]
dRlj22                        dRlj22                        dRlj22                        dRlj22                                                          'F'    [0.400301247835,5.37719631195]
dRlj23                        dRlj23                        dRlj23                        dRlj23                                                          'F'    [0.400580734015,5.38203430176]
dRlb11                        dRlb11                        dRlb11                        dRlb11                                                          'F'    [0.400195807219,5.26424264908]
dRlb21                        dRlb21                        dRlb21                        dRlb21                                                          'F'    [0.400000184774,5.4061126709]
MSSSF                         MSSSF                         MSSSF                         MSSSF                                                           'F'    [4.02011299133,586.325866699]
Mbl11                         Mbl11                         Mbl11                         Mbl11                                                           'F'    [13.8539085388,1656.56530762]
Mbl12                         Mbl12                         Mbl12                         Mbl12                                                           'F'    [9.86602306366,906.669189453]
Mllb1                         Mllb1                         Mllb1                         Mllb1                                                           'F'    [23.5393028259,1693.21569824]
MTvl1                         MTvl1                         MTvl1                         MTvl1                                                           'F'    [8.4366016381e-05,812.348022461]
MTvl2                         MTvl2                         MTvl2                         MTvl2                                                           'F'    [0.0061067705974,531.094665527]
Mlj11                         Mlj11                         Mlj11                         Mlj11                                                           'F'    [17.9352416992,1656.56530762]
Mlj12                         Mlj12                         Mlj12                         Mlj12                                                           'F'    [13.756310463,1207.78283691]
Mlj13                         Mlj13                         Mlj13                         Mlj13                                                           'F'    [11.8492107391,1097.97851562]
Mlj21                         Mlj21                         Mlj21                         Mlj21                                                           'F'    [9.11752796173,1274.35241699]
Mlj22                         Mlj22                         Mlj22                         Mlj22                                                           'F'    [9.4192609787,760.050842285]
Mlj23                         Mlj23                         Mlj23                         Mlj23                                                           'F'    [9.14548778534,765.029968262]
Mllj1                         Mllj1                         Mllj1                         Mllj1                                                           'F'    [36.2082901001,1776.16833496]
Mllj2                         Mllj2                         Mllj2                         Mllj2                                                           'F'    [23.5393028259,1376.06481934]
Mllj3                         Mllj3                         Mllj3                         Mllj3                                                           'F'    [28.5556812286,1148.63024902]
Mlljj12                       Mlljj12                       Mlljj12                       Mlljj12                                                         'F'    [78.4209518433,3302.25268555]
Mlljj13                       Mlljj13                       Mlljj13                       Mlljj13                                                         'F'    [84.3479919434,2123.27685547]
Mlljj23                       Mlljj23                       Mlljj23                       Mlljj23                                                         'F'    [66.3885574341,1840.65551758]
Mljj112                       Mljj112                       Mljj112                       Mljj112                                                         'F'    [49.3322677612,3244.23632812]
Mljj113                       Mljj113                       Mljj113                       Mljj113                                                         'F'    [42.1763343811,1938.22851562]
Mljj123                       Mljj123                       Mljj123                       Mljj123                                                         'F'    [36.7750205994,1806.5213623]
Mljj212                       Mljj212                       Mljj212                       Mljj212                                                         'F'    [39.3802070618,3240.51367188]
Mljj213                       Mljj213                       Mljj213                       Mljj213                                                         'F'    [38.9277877808,1853.75244141]
Mljj223                       Mljj223                       Mljj223                       Mljj223                                                         'F'    [27.4509944916,1603.30822754]
Mjj12                         Mjj12                         Mjj12                         Mjj12                                                           'F'    [17.7010211945,3182.25708008]
Mjj13                         Mjj13                         Mjj13                         Mjj13                                                           'F'    [20.5879268646,1758.97180176]
Mjj23                         Mjj23                         Mjj23                         Mjj23                                                           'F'    [15.8111629486,1569.22595215]
HT                            HT                            HT                            HT                                                              'F'    [77.2579269409,2294.91650391]
MET2HT                        MET2HT                        MET2HT                        MET2HT                                                          'F'    [0.000300817482639,1696.20458984]
MllW_2jL                      MllW_2jL                      MllW_2jL                      MllW_2jL                                                        'F'    [59.8283576965,1385.69995117]
MllW_1jL                      MllW_1jL                      MllW_1jL                      MllW_1jL                                                        'F'    [8.04352283478,586.325866699]
MllW1_H                       MllW1_H                       MllW1_H                       MllW1_H                                                         'F'    [77.9684371948,1549.93908691]
Ml1W_2jL                      Ml1W_2jL                      Ml1W_2jL                      Ml1W_2jL                                                        'F'    [27.726234436,1370.94238281]
Ml1W_1jL                      Ml1W_1jL                      Ml1W_1jL                      Ml1W_1jL                                                        'F'    [11.8492107391,1656.56530762]
Ml2W_2jL                      Ml2W_2jL                      Ml2W_2jL                      Ml2W_2jL                                                        'F'    [21.1876487732,1175.76672363]
Ml2W_1jL                      Ml2W_1jL                      Ml2W_1jL                      Ml2W_1jL                                                        'F'    [8.59082317352,1021.68920898]
Ml1W1_H                       Ml1W1_H                       Ml1W1_H                       Ml1W1_H                                                         'F'    [48.8301086426,1386.17700195]
Ml1W2_H                       Ml1W2_H                       Ml1W2_H                       Ml1W2_H                                                         'F'    [-1,1957.13024902]
Ml2W1_H                       Ml2W1_H                       Ml2W1_H                       Ml2W1_H                                                         'F'    [37.5239830017,1011.8416748]
Ml2W2_H                       Ml2W2_H                       Ml2W2_H                       Ml2W2_H                                                         'F'    [-1,1941.37585449]
MjjW1                         MjjW1                         MjjW1                         MjjW1                                                           'F'    [17.6307811737,899.778808594]
MjjW2                         MjjW2                         MjjW2                         MjjW2                                                           'F'    [-1,1888.078125]
Ptb2                          Ptb2                          Ptb2                          Ptb2                                                            'F'    [-1,655.882995605]
Mbl21                         Mbl21                         Mbl21                         Mbl21                                                           'F'    [-1,641.595031738]
Mbl22                         Mbl22                         Mbl22                         Mbl22                                                           'F'    [-1,538.649597168]
Mllb2                         Mllb2                         Mllb2                         Mllb2                                                           'F'    [-1,716.596130371]
Mllj4                         Mllj4                         Mllj4                         Mllj4                                                           'F'    [-1,1138.1652832]
Mlljj14                       Mlljj14                       Mlljj14                       Mlljj14                                                         'F'    [-1,2309.16040039]
Mlljj24                       Mlljj24                       Mlljj24                       Mlljj24                                                         'F'    [-1,2257.3659668]
Mlljj34                       Mlljj34                       Mlljj34                       Mlljj34                                                         'F'    [-1,1780.98657227]
Mljj114                       Mljj114                       Mljj114                       Mljj114                                                         'F'    [-1,2268.63134766]
Mljj124                       Mljj124                       Mljj124                       Mljj124                                                         'F'    [-1,2210.80419922]
Mljj134                       Mljj134                       Mljj134                       Mljj134                                                         'F'    [-1,1742.1965332]
Mljj214                       Mljj214                       Mljj214                       Mljj214                                                         'F'    [-1,2287.34155273]
Mljj224                       Mljj224                       Mljj224                       Mljj224                                                         'F'    [-1,2230.08422852]
Mljj234                       Mljj234                       Mljj234                       Mljj234                                                         'F'    [-1,1623.29443359]
Mjj14                         Mjj14                         Mjj14                         Mjj14                                                           'F'    [-1,2246.80151367]
Mjj24                         Mjj24                         Mjj24                         Mjj24                                                           'F'    [-1,2183.33422852]
Mjj34                         Mjj34                         Mjj34                         Mjj34                                                           'F'    [-1,1581.3527832]
MllW2_H                       MllW2_H                       MllW2_H                       MllW2_H                                                         'F'    [-1,2035.47497559]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTGNode

#ifndef BDTGNode__def
#define BDTGNode__def

class BDTGNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 81 )
   {
      // the training input variables
      const char* inputVars[] = { "Nj", "Nb", "Ptl1", "Ptl2", "Ptj1", "Ptj2", "Ptj3", "Ptb1", "dEtall", "dRll", "dRjj12", "dRjj23", "dRjj13", "dRlj11", "dRlj12", "dRlj13", "dRlj21", "dRlj22", "dRlj23", "dRlb11", "dRlb21", "MSSSF", "Mbl11", "Mbl12", "Mllb1", "MTvl1", "MTvl2", "Mlj11", "Mlj12", "Mlj13", "Mlj21", "Mlj22", "Mlj23", "Mllj1", "Mllj2", "Mllj3", "Mlljj12", "Mlljj13", "Mlljj23", "Mljj112", "Mljj113", "Mljj123", "Mljj212", "Mljj213", "Mljj223", "Mjj12", "Mjj13", "Mjj23", "HT", "MET2HT", "MllW_2jL", "MllW_1jL", "MllW1_H", "Ml1W_2jL", "Ml1W_1jL", "Ml2W_2jL", "Ml2W_1jL", "Ml1W1_H", "Ml1W2_H", "Ml2W1_H", "Ml2W2_H", "MjjW1", "MjjW2", "Ptb2", "Mbl21", "Mbl22", "Mllb2", "Mllj4", "Mlljj14", "Mlljj24", "Mlljj34", "Mljj114", "Mljj124", "Mljj134", "Mljj214", "Mljj224", "Mljj234", "Mjj14", "Mjj24", "Mjj34", "MllW2_H" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;
      fVmin[61] = 0;
      fVmax[61] = 0;
      fVmin[62] = 0;
      fVmax[62] = 0;
      fVmin[63] = 0;
      fVmax[63] = 0;
      fVmin[64] = 0;
      fVmax[64] = 0;
      fVmin[65] = 0;
      fVmax[65] = 0;
      fVmin[66] = 0;
      fVmax[66] = 0;
      fVmin[67] = 0;
      fVmax[67] = 0;
      fVmin[68] = 0;
      fVmax[68] = 0;
      fVmin[69] = 0;
      fVmax[69] = 0;
      fVmin[70] = 0;
      fVmax[70] = 0;
      fVmin[71] = 0;
      fVmax[71] = 0;
      fVmin[72] = 0;
      fVmax[72] = 0;
      fVmin[73] = 0;
      fVmax[73] = 0;
      fVmin[74] = 0;
      fVmax[74] = 0;
      fVmin[75] = 0;
      fVmax[75] = 0;
      fVmin[76] = 0;
      fVmax[76] = 0;
      fVmin[77] = 0;
      fVmax[77] = 0;
      fVmin[78] = 0;
      fVmax[78] = 0;
      fVmin[79] = 0;
      fVmax[79] = 0;
      fVmin[80] = 0;
      fVmax[80] = 0;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'F';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';
      fType[61] = 'F';
      fType[62] = 'F';
      fType[63] = 'F';
      fType[64] = 'F';
      fType[65] = 'F';
      fType[66] = 'F';
      fType[67] = 'F';
      fType[68] = 'F';
      fType[69] = 'F';
      fType[70] = 'F';
      fType[71] = 'F';
      fType[72] = 'F';
      fType[73] = 'F';
      fType[74] = 'F';
      fType[75] = 'F';
      fType[76] = 'F';
      fType[77] = 'F';
      fType[78] = 'F';
      fType[79] = 'F';
      fType[80] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[81];
   double fVmax[81];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[81];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDTG::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590492,0.0180984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.86323,0.072646) , 
3, 20.1463, 1, 0, 0.696691,0.0303666) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25688,-0.048624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640552,0.0281104) , 
3, 21.6997, 1, 0, 0.347069,0) , 
49, 20.1074, 1, 0, 0.596328,0.588965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116861,-0.0766279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0352117,-0.0929577) , 
8, 1.17538, 1, 0, 0.0576405,1.01556e+12) , 
21, 73.205, 1, 0, 0.490057,0.490057)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573383,0.0128712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844677,0.0638511) , 
3, 15.0826, 1, 0, 0.7411,0.201712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308196,-0.0373269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714957,0.0433936) , 
64, 18.9559, 1, 0, 0.405174,0.161184) , 
49, 12.4931, 1, 0, 0.60395,0.603476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206147,-0.0521986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0440953,-0.0827876) , 
8, 1.05937, 1, 0, 0.082652,2.76628e+08) , 
21, 72.4936, 1, 0, 0.513283,0.513283)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587892,0.0108234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261458,-0.0418401) , 
49, 16.7951, 1, 0, 0.463739,0.161894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0401451,-0.0778129) , 
21, 74.8587, 1, 0, 0.38937,0.0070609) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893115,0.0706483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553816,0.00917181) , 
49, 24.9217, 1, 0, 0.835954,0.392607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225059,-0.0411598) , 
21, 71.5314, 1, 0, 0.758545,3.16336e+15) , 
66, 69.1212, 1, 0, 0.492816,0.0299947)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688578,0.0287135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272958,-0.0370017) , 
21, 65.2378, 1, 0, 0.588933,0.0832966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327522,-0.0302563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0616717,-0.0707642) , 
21, 68.2976, 1, 0, 0.257352,116999) , 
49, 7.67393, 1, 0, 0.378767,0.444667) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866964,0.0600981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515375,0.00125087) , 
49, 30.8603, 1, 0, 0.820426,0.390828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311539,-0.0286715) , 
21, 67.79, 1, 0, 0.742469,0) , 
65, 9.68613, 1, 0, 0.483721,0.341848)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668368,0.0237041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927687,0.0675272) , 
64, 49.8986, 1, 0, 0.755018,1.29284e+21) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312522,-0.0298542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74886,0.0492054) , 
3, 25.0311, 1, 0, 0.381217,0.000453912) , 
49, 13.3464, 1, 0, 0.601352,0.0167638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0275479,-0.0720571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130027,-0.0505505) , 
3, 24.3058, 1, 0, 0.0685577,1.32379e+13) , 
21, 73.323, 1, 0, 0.511589,-4.16844e-07)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703197,0.0257347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35344,-0.0249733) , 
49, 7.11445, 1, 0, 0.48995,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.849913,0.0540878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47213,-0.00158559) , 
49, 33.5107, 1, 0, 0.79754,0.000769842) , 
3, 20.1499, 1, 0, 0.601372,18095.7) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22275,-0.0350964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0646393,-0.0603752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0266514,-0.0687276) , 
20, 2.44927, 1, 0, 0.0431699,1.87342e+14) , 
21, 80.7319, 1, 0, 0.0867128,3.49891e+12) , 
21, 71.5037, 1, 0, 0.501353,0.0731907)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491791,-0.0104309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771241,0.0376417) , 
3, 14.3605, 1, 0, 0.676251,340.581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222718,-0.0431488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535296,0.0193268) , 
25, 120.664, 1, 0, 0.285871,9.15136e-05) , 
49, 23.0212, 1, 0, 0.571902,2.51017e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0475928,-0.060762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0357945,-0.0633527) , 
12, 2.39514, 1, 0, 0.0416116,3.66899e+08) , 
21, 77.9449, 1, 0, 0.491736,1.81337e+18)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354408,-0.0259516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.755976,0.0364718) , 
66, 101.264, 1, 0, 0.423561,7.52767e-35) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793353,0.0394006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366682,-0.0142849) , 
49, 30.6948, 1, 0, 0.719733,0) , 
3, 15.0151, 1, 0, 0.602036,1.12668e+16) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0261905,-0.0629665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144471,-0.0358949) , 
3, 24.2658, 1, 0, 0.0716787,6.22678e+12) , 
21, 73.3511, 1, 0, 0.510841,0.000135858)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386343,-0.0203007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748514,0.0347859) , 
3, 20.1552, 1, 0, 0.506647,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0475124,-0.0554616) , 
21, 73.225, 1, 0, 0.412554,1.29539e+19) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561556,-0.00584964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.897482,0.0562675) , 
21, 27.9304, 1, 0, 0.861414,8.28968e+18) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228285,-0.02195) , 
21, 70.2156, 1, 0, 0.774838,69381.8) , 
65, 22.6125, 1, 0, 0.512997,0)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438408,-0.0100651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578671,0.0120715) , 
6, 33.9762, 1, 0, 0.508355,1.3193e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923822,0.0701237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720266,0.0349602) , 
8, 0.95263, 1, 0, 0.85624,1.00519e+17) , 
67, 66.1625, 1, 0, 0.749485,1.39254e-05) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288699,-0.0316384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500827,0.00083313) , 
3, 21.7327, 1, 0, 0.359513,inf) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783593,0.0335171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249474,-0.0396585) , 
8, 1.67706, 1, 0, 0.694796,1.06373e-34) , 
66, 77.154, 1, 0, 0.451768,22311.4) , 
56, 29.1449, 1, 0, 0.501697,4.15758e+12)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195307,-0.0448741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402734,-0.0144089) , 
3, 19.4615, 1, 0, 0.274357,6.28086e+11) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582884,0.0142966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192845,-0.0350779) , 
49, 23.0242, 1, 0, 0.485951,2.64919e+14) , 
71, 120.558, 1, 0, 0.390446,1.48615e+08) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663824,0.00662584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867938,0.0492222) , 
21, 32.1979, 1, 0, 0.838328,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330661,-0.0208473) , 
8, 1.67728, 1, 0, 0.771778,0.0431809) , 
66, 62.9442, 1, 0, 0.499137,2870.2)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548727,-0.0122352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.832584,0.0394076) , 
21, 32.2487, 1, 0, 0.783967,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282719,-0.0202104) , 
21, 67.3842, 1, 0, 0.695789,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479202,0.00606945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231656,-0.0335806) , 
56, 29.0859, 1, 0, 0.263558,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783749,0.0320826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332071,-0.0186329) , 
21, 63.3655, 1, 0, 0.658865,0.75702) , 
66, 67.5711, 1, 0, 0.350574,67877.1) , 
49, 7.67393, 1, 0, 0.493317,33416.5)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665408,0.0116205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289132,-0.024118) , 
49, 16.7944, 1, 0, 0.527593,1.06009e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857866,0.0462961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.965381,0.0714936) , 
56, 109.422, 1, 0, 0.906273,0.559074) , 
3, 30.2951, 1, 0, 0.576875,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0691082,-0.0450501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0322129,-0.0553255) , 
21, 101.892, 1, 0, 0.0486403,1.44194e+13) , 
21, 76.8878, 1, 0, 0.497211,0.00015843)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607989,0.0196677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26704,-0.0308862) , 
56, 24.6277, 1, 0, 0.314312,2.71445e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672316,0.0197577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0506549,-0.0476601) , 
21, 78.5053, 1, 0, 0.531664,2.71369e+19) , 
3, 18.4554, 1, 0, 0.410426,0.000209159) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978486,0.0667952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.80813,0.0318814) , 
56, 27.0292, 1, 0, 0.84345,2.03956e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350998,-0.0275062) , 
8, 1.64042, 1, 0, 0.779225,20.0968) , 
64, 60.9802, 1, 0, 0.496088,0)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41151,-0.0310044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767837,0.0260155) , 
21, 24.614, 1, 0, 0.74197,9.88219e-27) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0833369,-0.0399862) , 
21, 72.851, 1, 0, 0.644631,0.000396211) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414623,-0.00339346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629234,0.0358958) , 
19, 1.99011, 1, 0, 0.521985,1.1174e+09) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213834,-0.0338193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49728,0.0252623) , 
3, 35.3407, 1, 0, 0.238607,7.87206e+13) , 
56, 29.7487, 1, 0, 0.274202,1.69704e+12) , 
49, 15.3482, 1, 0, 0.496554,0)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220834,-0.0489029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772269,0.0362423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326269,-0.0196893) , 
9, 1.37321, 1, 0, 0.392521,2.087e+13) , 
21, 33.9731, 1, 0, 0.360105,2.62541e+12) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874464,0.0506843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626872,0.00957947) , 
56, 28.3175, 1, 0, 0.679756,0.320245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0543231,-0.0448435) , 
21, 76.4581, 1, 0, 0.596921,3.25288e+12) , 
62, 49.6373, 1, 0, 0.49993,0)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555293,0.00679264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947357,0.0702911) , 
3, 15.6404, 1, 0, 0.71766,1.47541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298775,-0.0229574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522982,0.0117834) , 
3, 25.7475, 1, 0, 0.347877,3.13733e+12) , 
56, 22.8058, 1, 0, 0.381221,1637.31) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.883943,0.0439182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643176,-0.00419523) , 
51, 101.56, 1, 0, 0.853515,5.33881e+16) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680625,0.0234492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270475,-0.0314827) , 
35, 142.999, 1, 0, 0.447957,0) , 
8, 1.3716, 1, 0, 0.763708,0) , 
64, 28.0945, 1, 0, 0.487724,0)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852464,0.0423717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495704,-0.00267871) , 
49, 7.83979, 1, 0, 0.659928,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27703,-0.032367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380353,-0.00278931) , 
19, 2.68334, 1, 0, 0.301346,8.54265e+21) , 
56, 23.1532, 1, 0, 0.351157,35182) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538717,-0.00101237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798047,0.0323843) , 
77, 56.1594, 1, 0, 0.694571,3.76178e+18) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0640196,-0.039249) , 
21, 78.9999, 1, 0, 0.589659,1.42603e+13) , 
3, 15.0181, 1, 0, 0.496828,0)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230332,-0.0435187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376858,-0.011898) , 
21, 28.68, 1, 0, 0.362561,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.886028,0.0645664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442232,0.00537691) , 
9, 1.21785, 1, 0, 0.607251,0) , 
22, 170.134, 1, 0, 0.386145,3.5413e+06) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747637,0.0185405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352495,-0.0375629) , 
49, 11.3551, 1, 0, 0.571137,274583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.850062,0.0353409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490117,-0.00696979) , 
51, 101.336, 1, 0, 0.797154,52.9338) , 
3, 12.8398, 1, 0, 0.749964,16.0577) , 
65, 15.0292, 1, 0, 0.490494,0)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732433,0.0243974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558226,-0.0109231) , 
18, 2.27181, 1, 0, 0.641012,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83893,0.051257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.804835,0.0213994) , 
66, 131.124, 1, 0, 0.831645,0) , 
19, 2.61172, 1, 0, 0.694586,4.48981e+11) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204711,-0.03061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566122,0.000207432) , 
63, 29.6325, 1, 0, 0.271467,0.000310231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811443,0.0386449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353721,-0.012344) , 
9, 1.48043, 1, 0, 0.524819,0) , 
3, 21.8245, 1, 0, 0.3448,0) , 
49, 7.67393, 1, 0, 0.489185,351234)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.965603,0.0715971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.79149,0.0317974) , 
15, 1.50296, 1, 0, 0.839574,1.44861e+18) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537484,-0.00839828) , 
9, 2.36282, 1, 0, 0.769341,1.32777e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185379,-0.051408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555791,0.0049478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150728,-0.0377729) , 
8, 1.64361, 1, 0, 0.467813,1.4469e+18) , 
21, 24.0695, 1, 0, 0.446481,1.261e+06) , 
56, 28.6131, 1, 0, 0.495207,0)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58668,-0.00140946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874962,0.0478159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680026,0.0126544) , 
51, 87.3795, 1, 0, 0.829548,0) , 
47, 75.8949, 1, 0, 0.766473,5.72327e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213033,-0.0429008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783996,0.0302033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37575,-0.0131173) , 
9, 1.36245, 1, 0, 0.454684,6.96933e+19) , 
21, 27.1509, 1, 0, 0.432383,0) , 
56, 28.3175, 1, 0, 0.483993,3.16627e+07)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787493,0.0286606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65836,-0.0025701) , 
45, 273.35, 1, 0, 0.752011,1.97428e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725088,0.0362262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206842,-0.0306921) , 
9, 1.87416, 1, 0, 0.313615,1.46302e+12) , 
21, 64.6713, 1, 0, 0.650554,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356386,-0.0116345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626506,0.0346314) , 
25, 119.717, 1, 0, 0.426041,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322812,-0.00961841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111153,-0.0409079) , 
33, 144.937, 1, 0, 0.167819,3.90366e+18) , 
9, 2.01237, 1, 0, 0.287673,1.64895e+21) , 
49, 15.9453, 1, 0, 0.511088,0)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243494,-0.0303681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641232,0.00608972) , 
63, 30.1357, 1, 0, 0.3044,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565308,0.0207754) , 
30, 127.908, 1, 0, 0.337547,1.75621e+12) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749729,0.0238642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231825,-0.0282498) , 
8, 1.79665, 1, 0, 0.692575,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2221,-0.0280489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505032,0.0235658) , 
25, 125.511, 1, 0, 0.275648,1.48959e+13) , 
49, 21.5797, 1, 0, 0.592599,0.0147288) , 
73, 76.3994, 1, 0, 0.493427,6.51741e+18)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726332,0.0240028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326838,-0.0165141) , 
56, 22.5482, 1, 0, 0.361021,49998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843878,0.0304017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540387,-0.0117099) , 
24, 163.136, 1, 0, 0.764541,0.0722034) , 
66, 65.9727, 1, 0, 0.461869,3.40699e+21) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810782,0.0305658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.913417,0.0648261) , 
25, 77.4811, 1, 0, 0.853654,9.00578e+08) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339647,-0.000679951) , 
9, 2.05144, 1, 0, 0.701342,0.189851) , 
22, 163.363, 1, 0, 0.496647,1.44315e+18)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224542,-0.0385998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558938,0.00323475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.889874,0.0386638) , 
3, 24.6234, 1, 0, 0.629751,0) , 
21, 21.9437, 1, 0, 0.599517,0.000223942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679599,0.0199557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116159,-0.0371935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30405,-0.0071732) , 
66, 135.536, 1, 0, 0.141171,2.44667e+08) , 
9, 1.91544, 1, 0, 0.228121,1.0061e+14) , 
21, 64.1928, 1, 0, 0.498162,0)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713138,0.00492402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866544,0.0343704) , 
19, 2.1509, 1, 0, 0.785051,1.21115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150373,-0.0269994) , 
21, 70.2488, 1, 0, 0.670075,2.21003e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743882,0.0289297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317637,-0.0184272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452652,0.018238) , 
25, 129.223, 1, 0, 0.334177,0.00595871) , 
56, 22.9513, 1, 0, 0.366181,5.13931e+18) , 
49, 7.19344, 1, 0, 0.49124,1.52644e+18)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262071,-0.0224111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48634,0.0190641) , 
22, 151.714, 1, 0, 0.284425,5.1479e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79055,0.0304168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495861,-0.0209064) , 
24, 163.203, 1, 0, 0.674695,7.83389e+19) , 
63, 30.2037, 1, 0, 0.371753,1.53998e+07) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495916,-0.0100224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787916,0.0281423) , 
21, 32.9726, 1, 0, 0.749059,7.88496e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596212,0.0290194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11849,-0.0290351) , 
9, 1.9667, 1, 0, 0.200104,6.53355e+12) , 
21, 67.5037, 1, 0, 0.602272,1.76021e+06) , 
3, 15.0736, 1, 0, 0.514843,0)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23358,-0.0393252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3989,-0.0107194) , 
21, 29.017, 1, 0, 0.378292,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.845407,0.0350497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456395,-0.00930999) , 
51, 90.2732, 1, 0, 0.743947,1.59043) , 
66, 118.585, 1, 0, 0.430299,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562654,-6.92177e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.879027,0.041993) , 
21, 29.044, 1, 0, 0.810791,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650869,0.0195815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31925,-0.0261917) , 
25, 60.8203, 1, 0, 0.478675,2.3096e+20) , 
9, 1.85873, 1, 0, 0.652215,3.36032e+06) , 
0, 5, 1, 0, 0.501521,-0.00860171)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307061,-0.0203199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267975,-0.0541891) , 
43, 195.171, 1, 0, 0.293666,391296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788993,0.0223901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369113,-0.0124445) , 
9, 1.33055, 1, 0, 0.433762,-6.74949e-07) , 
21, 33.0175, 1, 0, 0.411343,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962383,0.0632293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572419,0.0190796) , 
49, 7.46875, 1, 0, 0.771938,3.26111e+13) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.842622,0.0296703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479973,-0.00777435) , 
9, 1.29636, 1, 0, 0.595021,7.56087e+11) , 
57, 130.774, 1, 0, 0.630212,2.03696e+13) , 
0, 5, 1, 0, 0.481079,-0.0163863)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26927,-0.0324422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531703,0.000386103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689024,0.0229363) , 
19, 2.47103, 1, 0, 0.584446,4.47199e+11) , 
21, 24.0004, 1, 0, 0.560013,1.38391e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247476,-0.0347561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0286599,-0.0415978) , 
21, 71.0411, 1, 0, 0.104172,1.09087e+09) , 
8, 1.89668, 1, 0, 0.498766,4.81015e+06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25212,-0.0241607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696568,0.017772) , 
66, 86.0646, 1, 0, 0.318381,9.18205e+13) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654978,0.0357118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324795,-0.0199004) , 
10, 2.89592, 1, 0, 0.519345,-0.000912961) , 
30, 111.004, 1, 0, 0.361691,1.77593e+12) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771159,0.0184239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358937,-0.00820618) , 
49, 23.0212, 1, 0, 0.68909,4.25752e+19) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0485301,-0.0377818) , 
21, 76.8878, 1, 0, 0.596454,1.46386e+11) , 
67, 63.611, 1, 0, 0.505297,1.08162e+06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298369,-0.0236062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776074,0.0452242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662651,0.0122722) , 
16, 1.09658, 1, 0, 0.673235,2.15008e+18) , 
21, 24.9199, 1, 0, 0.63465,3.55925e-35) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716662,0.024276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236715,-0.0100902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115695,-0.0407694) , 
20, 2.23658, 1, 0, 0.169487,9.23721e-10) , 
9, 1.74614, 1, 0, 0.246576,4.08574e+19) , 
21, 64.0789, 1, 0, 0.527421,1.12177e+06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717873,-0.00094475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.827788,0.0330271) , 
8, 0.311178, 1, 0, 0.799929,4.58666e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416486,-0.0257186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611526,0.0108388) , 
78, 79.0024, 1, 0, 0.522022,0.194815) , 
51, 86.6511, 1, 0, 0.699579,0.0299047) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173302,-0.0405929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362436,-0.0111017) , 
3, 11.3642, 1, 0, 0.337581,1.20013e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73615,0.0527356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391383,0.00257735) , 
8, 0.432012, 1, 0, 0.478669,3.11753e+20) , 
25, 112.618, 1, 0, 0.365002,2.01582e+06) , 
49, 7.67519, 1, 0, 0.504407,3.88421e+18)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239293,-0.042679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488169,0.00844094) , 
29, 107.347, 1, 0, 0.311754,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429506,-0.00664739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744669,0.0239476) , 
6, 32.3809, 1, 0, 0.678551,1.20687e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442572,-0.00431311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309253,-0.0488048) , 
71, 433.134, 1, 0, 0.432789,9.1548e-05) , 
8, 0.639203, 1, 0, 0.521118,1.3866e+17) , 
21, 27.2872, 1, 0, 0.500186,2.22945e+19)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586821,0.0084783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38112,-0.0334008) , 
53, 196.251, 1, 0, 0.5387,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47707,-0.0103211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779599,0.0362613) , 
5, 46.4786, 1, 0, 0.713376,0.00026881) , 
19, 1.85346, 1, 0, 0.634907,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67554,0.0294337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438317,-0.0147547) , 
15, 2.70117, 1, 0, 0.581281,1.18293e+20) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354409,-0.0171655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727907,0.0213157) , 
65, 61.6941, 1, 0, 0.399129,2.32854e+18) , 
25, 33.0454, 1, 0, 0.440357,5074.16) , 
8, 0.573516, 1, 0, 0.509549,1.4979e+08)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247025,-0.0414996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416772,0.00226495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277046,-0.0332663) , 
10, 2.45558, 1, 0, 0.342203,0.114647) , 
21, 39.6191, 1, 0, 0.314837,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699038,0.0179665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265475,-0.0269769) , 
49, 46.0423, 1, 0, 0.654104,5.02436e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331687,-0.0132009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735625,0.0179988) , 
65, 32.4369, 1, 0, 0.424685,0.000265599) , 
8, 0.684858, 1, 0, 0.520252,0) , 
6, 30.8448, 1, 0, 0.48925,1.4163e+18)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872147,0.0379876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555455,0.00738147) , 
9, 1.67393, 1, 0, 0.721433,6.04935e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42106,-0.0287607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612946,0.00537171) , 
3, 11.4774, 1, 0, 0.588747,4.38868e+08) , 
10, 2.48291, 1, 0, 0.643358,2.66491e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590083,0.0184514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211626,-0.0275742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323769,-0.00380243) , 
25, 100.189, 1, 0, 0.248479,1.38061e+08) , 
56, 26.8908, 1, 0, 0.283942,7.70051e+19) , 
49, 13.4042, 1, 0, 0.484351,8.5941e+10)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376983,-0.0303706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669548,0.0427951) , 
54, 70.3641, 1, 0, 0.518647,1.97488e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280548,-0.0286465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198375,-0.0499836) , 
10, 2.48706, 1, 0, 0.23118,-4.29352e-06) , 
56, 42.3655, 1, 0, 0.350552,3.40055e+20) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688433,0.0172252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537053,-0.0202133) , 
50, 266.174, 1, 0, 0.670061,1.60454e+09) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524164,0.0144083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303416,-0.0182858) , 
25, 42.2748, 1, 0, 0.367403,1.01316e-28) , 
8, 0.867502, 1, 0, 0.511478,1.24112e+06) , 
21, 31.7632, 1, 0, 0.485975,0.000256679)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209419,-0.0345946) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45965,-0.00292522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715207,0.0179042) , 
3, 16.1981, 1, 0, 0.605836,0.000212059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557923,0.00364149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26023,-0.0231836) , 
8, 0.684885, 1, 0, 0.354859,4.58306e+18) , 
51, 89.1914, 1, 0, 0.522393,1.14664e+19) , 
21, 22.5155, 1, 0, 0.50149,5.74739e+10)    );
   return;
};

// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
