// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/00       [399360]
Creator        : jbhyun
Date           : Tue Jun  8 15:53:49 2021
Host           : Linux root-ubuntu-2004-1 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jbhyun/Forge/BDTTrain/tmva
Training events: 12090
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "40" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
BaggedSampleFraction: "1.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "9" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "1.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 81
Nj                            Nj                            Nj                            Nj                                                              'I'    [3,11]
Nb                            Nb                            Nb                            Nb                                                              'I'    [1,5]
Ptl1                          Ptl1                          Ptl1                          Ptl1                                                            'F'    [25.0006752014,590.201049805]
Ptl2                          Ptl2                          Ptl2                          Ptl2                                                            'F'    [15.0003347397,171.046890259]
Ptj1                          Ptj1                          Ptj1                          Ptj1                                                            'F'    [27.1468791962,737.51739502]
Ptj2                          Ptj2                          Ptj2                          Ptj2                                                            'F'    [25.2826633453,480.504821777]
Ptj3                          Ptj3                          Ptj3                          Ptj3                                                            'F'    [25.0002841949,373.181671143]
Ptb1                          Ptb1                          Ptb1                          Ptb1                                                            'F'    [25.0033969879,630.906494141]
dEtall                        dEtall                        dEtall                        dEtall                                                          'F'    [4.7355890274e-05,4.50000667572]
dRll                          dRll                          dRll                          dRll                                                            'F'    [0.297354012728,5.17979860306]
dRjj12                        dRjj12                        dRjj12                        dRjj12                                                          'F'    [0.401978522539,5.21108150482]
dRjj23                        dRjj23                        dRjj23                        dRjj23                                                          'F'    [0.401176422834,5.3961853981]
dRjj13                        dRjj13                        dRjj13                        dRjj13                                                          'F'    [0.403728246689,5.55556678772]
dRlj11                        dRlj11                        dRlj11                        dRlj11                                                          'F'    [0.402498632669,5.17003488541]
dRlj12                        dRlj12                        dRlj12                        dRlj12                                                          'F'    [0.400317937136,5.18501901627]
dRlj13                        dRlj13                        dRlj13                        dRlj13                                                          'F'    [0.401918917894,5.4077296257]
dRlj21                        dRlj21                        dRlj21                        dRlj21                                                          'F'    [0.400806248188,5.28665542603]
dRlj22                        dRlj22                        dRlj22                        dRlj22                                                          'F'    [0.400134146214,5.48212337494]
dRlj23                        dRlj23                        dRlj23                        dRlj23                                                          'F'    [0.400983095169,5.42132329941]
dRlb11                        dRlb11                        dRlb11                        dRlb11                                                          'F'    [0.413394629955,5.09595346451]
dRlb21                        dRlb21                        dRlb21                        dRlb21                                                          'F'    [0.405257642269,5.18121528625]
MSSSF                         MSSSF                         MSSSF                         MSSSF                                                           'F'    [10.1058120728,737.557373047]
Mbl11                         Mbl11                         Mbl11                         Mbl11                                                           'F'    [15.1355419159,1022.82171631]
Mbl12                         Mbl12                         Mbl12                         Mbl12                                                           'F'    [11.2718009949,545.409423828]
Mllb1                         Mllb1                         Mllb1                         Mllb1                                                           'F'    [41.1215858459,1276.75036621]
MTvl1                         MTvl1                         MTvl1                         MTvl1                                                           'F'    [0.00479244720191,814.334899902]
MTvl2                         MTvl2                         MTvl2                         MTvl2                                                           'F'    [0.00109037535731,369.937866211]
Mlj11                         Mlj11                         Mlj11                         Mlj11                                                           'F'    [16.4049777985,1590.84851074]
Mlj12                         Mlj12                         Mlj12                         Mlj12                                                           'F'    [15.6494426727,867.578918457]
Mlj13                         Mlj13                         Mlj13                         Mlj13                                                           'F'    [13.3966522217,809.550415039]
Mlj21                         Mlj21                         Mlj21                         Mlj21                                                           'F'    [13.5696411133,1150.87609863]
Mlj22                         Mlj22                         Mlj22                         Mlj22                                                           'F'    [11.5061693192,1036.5880127]
Mlj23                         Mlj23                         Mlj23                         Mlj23                                                           'F'    [11.2559423447,723.035095215]
Mllj1                         Mllj1                         Mllj1                         Mllj1                                                           'F'    [47.7027320862,1652.29663086]
Mllj2                         Mllj2                         Mllj2                         Mllj2                                                           'F'    [41.1215858459,1503.39355469]
Mllj3                         Mllj3                         Mllj3                         Mllj3                                                           'F'    [34.611831665,1135.76721191]
Mlljj12                       Mlljj12                       Mlljj12                       Mlljj12                                                         'F'    [76.176864624,3336.94775391]
Mlljj13                       Mlljj13                       Mlljj13                       Mlljj13                                                         'F'    [86.2977218628,2041.25183105]
Mlljj23                       Mlljj23                       Mlljj23                       Mlljj23                                                         'F'    [72.1586837769,1856.86096191]
Mljj112                       Mljj112                       Mljj112                       Mljj112                                                         'F'    [49.861125946,3322.43530273]
Mljj113                       Mljj113                       Mljj113                       Mljj113                                                         'F'    [44.7366828918,1922.68811035]
Mljj123                       Mljj123                       Mljj123                       Mljj123                                                         'F'    [41.3539657593,1755.15539551]
Mljj212                       Mljj212                       Mljj212                       Mljj212                                                         'F'    [43.8519515991,3208.36035156]
Mljj213                       Mljj213                       Mljj213                       Mljj213                                                         'F'    [44.5880126953,1793.23876953]
Mljj223                       Mljj223                       Mljj223                       Mljj223                                                         'F'    [29.2453250885,1702.15881348]
Mjj12                         Mjj12                         Mjj12                         Mjj12                                                           'F'    [19.5157394409,3194.25512695]
Mjj13                         Mjj13                         Mjj13                         Mjj13                                                           'F'    [19.2980918884,1670.65637207]
Mjj23                         Mjj23                         Mjj23                         Mjj23                                                           'F'    [15.6277399063,1599.87072754]
HT                            HT                            HT                            HT                                                              'F'    [79.8421707153,1836.00231934]
MET2HT                        MET2HT                        MET2HT                        MET2HT                                                          'F'    [0.00142327370122,1444.42895508]
MllW_2jL                      MllW_2jL                      MllW_2jL                      MllW_2jL                                                        'F'    [66.8877944946,980.953308105]
MllW_1jL                      MllW_1jL                      MllW_1jL                      MllW_1jL                                                        'F'    [15.8134250641,737.557373047]
MllW1_H                       MllW1_H                       MllW1_H                       MllW1_H                                                         'F'    [92.0417633057,1403.87329102]
Ml1W_2jL                      Ml1W_2jL                      Ml1W_2jL                      Ml1W_2jL                                                        'F'    [33.9582939148,916.282714844]
Ml1W_1jL                      Ml1W_1jL                      Ml1W_1jL                      Ml1W_1jL                                                        'F'    [12.3912248611,1590.84851074]
Ml2W_2jL                      Ml2W_2jL                      Ml2W_2jL                      Ml2W_2jL                                                        'F'    [28.7814025879,605.329040527]
Ml2W_1jL                      Ml2W_1jL                      Ml2W_1jL                      Ml2W_1jL                                                        'F'    [10.2800836563,1150.87609863]
Ml1W1_H                       Ml1W1_H                       Ml1W1_H                       Ml1W1_H                                                         'F'    [44.7932510376,1155.05944824]
Ml1W2_H                       Ml1W2_H                       Ml1W2_H                       Ml1W2_H                                                         'F'    [-1,1722.13146973]
Ml2W1_H                       Ml2W1_H                       Ml2W1_H                       Ml2W1_H                                                         'F'    [45.8832359314,1009.57727051]
Ml2W2_H                       Ml2W2_H                       Ml2W2_H                       Ml2W2_H                                                         'F'    [-1,1670.88745117]
MjjW1                         MjjW1                         MjjW1                         MjjW1                                                           'F'    [15.6277399063,445.802612305]
MjjW2                         MjjW2                         MjjW2                         MjjW2                                                           'F'    [-1,1638.65759277]
Ptb2                          Ptb2                          Ptb2                          Ptb2                                                            'F'    [-1,292.96975708]
Mbl21                         Mbl21                         Mbl21                         Mbl21                                                           'F'    [-1,840.321960449]
Mbl22                         Mbl22                         Mbl22                         Mbl22                                                           'F'    [-1,729.45300293]
Mllb2                         Mllb2                         Mllb2                         Mllb2                                                           'F'    [-1,1120.94897461]
Mllj4                         Mllj4                         Mllj4                         Mllj4                                                           'F'    [-1,899.477783203]
Mlljj14                       Mlljj14                       Mlljj14                       Mlljj14                                                         'F'    [-1,2290.85742188]
Mlljj24                       Mlljj24                       Mlljj24                       Mlljj24                                                         'F'    [-1,1680.71411133]
Mlljj34                       Mlljj34                       Mlljj34                       Mlljj34                                                         'F'    [-1,1723.17480469]
Mljj114                       Mljj114                       Mljj114                       Mljj114                                                         'F'    [-1,2277.09912109]
Mljj124                       Mljj124                       Mljj124                       Mljj124                                                         'F'    [-1,1109.48999023]
Mljj134                       Mljj134                       Mljj134                       Mljj134                                                         'F'    [-1,1622.62133789]
Mljj214                       Mljj214                       Mljj214                       Mljj214                                                         'F'    [-1,2105.87719727]
Mljj224                       Mljj224                       Mljj224                       Mljj224                                                         'F'    [-1,1275.64831543]
Mljj234                       Mljj234                       Mljj234                       Mljj234                                                         'F'    [-1,1541.51269531]
Mjj14                         Mjj14                         Mjj14                         Mjj14                                                           'F'    [-1,2092.41625977]
Mjj24                         Mjj24                         Mjj24                         Mjj24                                                           'F'    [-1,1026.0411377]
Mjj34                         Mjj34                         Mjj34                         Mjj34                                                           'F'    [-1,1429.2578125]
MllW2_H                       MllW2_H                       MllW2_H                       MllW2_H                                                         'F'    [-1,1754.01660156]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTGNode

#ifndef BDTGNode__def
#define BDTGNode__def

class BDTGNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 81 )
   {
      // the training input variables
      const char* inputVars[] = { "Nj", "Nb", "Ptl1", "Ptl2", "Ptj1", "Ptj2", "Ptj3", "Ptb1", "dEtall", "dRll", "dRjj12", "dRjj23", "dRjj13", "dRlj11", "dRlj12", "dRlj13", "dRlj21", "dRlj22", "dRlj23", "dRlb11", "dRlb21", "MSSSF", "Mbl11", "Mbl12", "Mllb1", "MTvl1", "MTvl2", "Mlj11", "Mlj12", "Mlj13", "Mlj21", "Mlj22", "Mlj23", "Mllj1", "Mllj2", "Mllj3", "Mlljj12", "Mlljj13", "Mlljj23", "Mljj112", "Mljj113", "Mljj123", "Mljj212", "Mljj213", "Mljj223", "Mjj12", "Mjj13", "Mjj23", "HT", "MET2HT", "MllW_2jL", "MllW_1jL", "MllW1_H", "Ml1W_2jL", "Ml1W_1jL", "Ml2W_2jL", "Ml2W_1jL", "Ml1W1_H", "Ml1W2_H", "Ml2W1_H", "Ml2W2_H", "MjjW1", "MjjW2", "Ptb2", "Mbl21", "Mbl22", "Mllb2", "Mllj4", "Mlljj14", "Mlljj24", "Mlljj34", "Mljj114", "Mljj124", "Mljj134", "Mljj214", "Mljj224", "Mljj234", "Mjj14", "Mjj24", "Mjj34", "MllW2_H" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;
      fVmin[61] = 0;
      fVmax[61] = 0;
      fVmin[62] = 0;
      fVmax[62] = 0;
      fVmin[63] = 0;
      fVmax[63] = 0;
      fVmin[64] = 0;
      fVmax[64] = 0;
      fVmin[65] = 0;
      fVmax[65] = 0;
      fVmin[66] = 0;
      fVmax[66] = 0;
      fVmin[67] = 0;
      fVmax[67] = 0;
      fVmin[68] = 0;
      fVmax[68] = 0;
      fVmin[69] = 0;
      fVmax[69] = 0;
      fVmin[70] = 0;
      fVmax[70] = 0;
      fVmin[71] = 0;
      fVmax[71] = 0;
      fVmin[72] = 0;
      fVmax[72] = 0;
      fVmin[73] = 0;
      fVmax[73] = 0;
      fVmin[74] = 0;
      fVmax[74] = 0;
      fVmin[75] = 0;
      fVmax[75] = 0;
      fVmin[76] = 0;
      fVmax[76] = 0;
      fVmin[77] = 0;
      fVmax[77] = 0;
      fVmin[78] = 0;
      fVmax[78] = 0;
      fVmin[79] = 0;
      fVmax[79] = 0;
      fVmin[80] = 0;
      fVmax[80] = 0;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'F';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';
      fType[61] = 'F';
      fType[62] = 'F';
      fType[63] = 'F';
      fType[64] = 'F';
      fType[65] = 'F';
      fType[66] = 'F';
      fType[67] = 'F';
      fType[68] = 'F';
      fType[69] = 'F';
      fType[70] = 'F';
      fType[71] = 'F';
      fType[72] = 'F';
      fType[73] = 'F';
      fType[74] = 'F';
      fType[75] = 'F';
      fType[76] = 'F';
      fType[77] = 'F';
      fType[78] = 'F';
      fType[79] = 'F';
      fType[80] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[81];
   double fVmax[81];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[81];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDTG::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.860895,0.072179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344914,-0.0310171) , 
21, 71.1721, 1, 0, 0.826184,0.0153426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134094,-0.0731811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508447,0.00168937) , 
25, 119.198, 1, 0, 0.222057,1.54998e+13) , 
49, 30.5842, 1, 0, 0.666333,5.26657e-09) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0224437,-0.0955113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0902442,-0.0819512) , 
79, 70.5389, 1, 0, 0.0389321,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125529,-0.0748942) , 
65, 23.7399, 1, 0, 0.0568554,-1.95283e-05) , 
21, 75.8374, 1, 0, 0.476783,0)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926476,0.080581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568405,0.00944998) , 
56, 28.8863, 1, 0, 0.628018,7.86726e+13) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540091,0.00161875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.968628,0.0880973) , 
40, 157.718, 1, 0, 0.901223,1.85729e-08) , 
19, 2.64148, 1, 0, 0.7036,-8.59994e-06) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320974,-0.0275547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0407115,-0.0840995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190683,-0.0547879) , 
64, 74.549, 1, 0, 0.0645352,5.45337e+15) , 
25, 66.6496, 1, 0, 0.0963407,2.44763e+14) , 
21, 73.3797, 1, 0, 0.573862,0)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477364,-0.0154462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.899233,0.0702298) , 
21, 37.1959, 1, 0, 0.814653,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229515,-0.0572981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697616,0.0310922) , 
22, 103.376, 1, 0, 0.380248,2.43994e+14) , 
49, 14.3029, 1, 0, 0.64797,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46292,0.00608244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225445,-0.0408344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0555099,-0.0763459) , 
31, 76.2717, 1, 0, 0.0868688,1.43589e+15) , 
50, 207.67, 1, 0, 0.131181,1.28243e+13) , 
21, 72.9147, 1, 0, 0.526068,0.144222)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816684,0.0546273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33133,-0.0401292) , 
18, 2.09881, 1, 0, 0.514449,2.70096e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897291,0.0664356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487896,-0.0101914) , 
8, 1.26078, 1, 0, 0.828291,0.872677) , 
21, 42.4593, 1, 0, 0.735818,-1.0292e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307985,-0.0202833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137229,-0.0571541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0193786,-0.0797859) , 
28, 118.373, 1, 0, 0.0469968,0) , 
55, 108.437, 1, 0, 0.0642066,-1.61947e-05) , 
21, 72.9242, 1, 0, 0.474848,-6.29281e-06)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898915,0.0632382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578103,-0.00323828) , 
5, 114.604, 1, 0, 0.830079,1.61557e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20618,-0.0639098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949538,0.0815076) , 
37, 317.265, 1, 0, 0.284065,4.1159e+15) , 
49, 20.2221, 1, 0, 0.657794,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0250138,-0.0756532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0855303,-0.0608296) , 
2, 90.0232, 1, 0, 0.038974,1.29617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163431,-0.0444643) , 
65, 82.3113, 1, 0, 0.0507935,-1.9614e-05) , 
21, 76.0237, 1, 0, 0.47269,0)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455506,-0.0262264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.959443,0.0731925) , 
30, 127.491, 1, 0, 0.55539,9.02825e+13) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704831,0.0227807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9695,0.076006) , 
52, 153.469, 1, 0, 0.93872,2.19505e+14) , 
66, 38.0133, 1, 0, 0.679822,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228105,-0.0284049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212651,-0.0347999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0343297,-0.0690727) , 
57, 147.995, 1, 0, 0.055571,1.18726e+15) , 
8, 0.697881, 1, 0, 0.079063,1.03836e+13) , 
21, 75.6985, 1, 0, 0.50361,4.30908e+13)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156454,-0.0745156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8101,0.0396794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35077,-0.0295308) , 
49, 23.7284, 1, 0, 0.69898,-1.02703e-05) , 
21, 26.7339, 1, 0, 0.651438,1.0364e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230555,-0.0195634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.042396,-0.06473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11112,-0.0458882) , 
18, 2.70281, 1, 0, 0.0572461,-2.175e-05) , 
19, 1.4238, 1, 0, 0.0729358,0) , 
21, 77.8297, 1, 0, 0.465486,4.64405e+16)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78855,0.040953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0888054,-0.0574673) , 
21, 69.1548, 1, 0, 0.518304,6.26828e+12) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51699,-0.000641563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18505,-0.0638531) , 
26, 25.0436, 1, 0, 0.233995,-1.0611e-05) , 
14, 1.97602, 1, 0, 0.312915,3.20428e+12) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927788,0.0653816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513346,-0.0209757) , 
29, 173.419, 1, 0, 0.844812,5.79637e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137792,-0.0790517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641579,0.0295769) , 
41, 159.258, 1, 0, 0.416602,2.63866e+15) , 
51, 90.0637, 1, 0, 0.694764,2.57188e+08) , 
66, 38.5225, 1, 0, 0.418661,0)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154949,-0.0765945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.878356,0.0482337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403499,-0.0207476) , 
49, 19.6313, 1, 0, 0.747978,0) , 
21, 29.6439, 1, 0, 0.651872,1.11722e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391086,0.0091904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0348232,-0.0714583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0551207,-0.0558551) , 
50, 185.766, 1, 0, 0.0499633,0) , 
9, 1.95654, 1, 0, 0.0765887,2.36991e+15) , 
21, 72.4125, 1, 0, 0.446867,-5.59607e-06)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537615,-0.0120885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.903118,0.0519706) , 
65, 50.5758, 1, 0, 0.618079,-1.0954e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993094,0.0705997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0886419) , 
49, 12.1333, 1, 0, 0.994967,9.43217e+15) , 
16, 3.02053, 1, 0, 0.674283,1.03088e+14) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194457,-0.0213285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0279672,-0.0613648) , 
39, 233.827, 1, 0, 0.0511891,-2.76199e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205447,-0.0174395) , 
48, 309.425, 1, 0, 0.0729035,1.10996e+13) , 
21, 76.3668, 1, 0, 0.5047,0)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496524,-0.0363704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931862,0.057617) , 
48, 189.018, 1, 0, 0.833407,2.97396e+12) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461089,0.00310585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0834899,-0.0572987) , 
49, 6.37968, 1, 0, 0.154038,3.61539e+19) , 
21, 68.9338, 1, 0, 0.59535,6.76857e+15) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613678,0.0320376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0725707,-0.103921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143334,-0.0484598) , 
9, 0.997224, 1, 0, 0.124234,0.0158618) , 
56, 44.2234, 1, 0, 0.178165,0) , 
49, 28.6067, 1, 0, 0.481941,1.89661e+18)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505776,-0.0201029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.999402,0.0767942) , 
37, 282.612, 1, 0, 0.847405,0.126841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656279,0.0137363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220277,-0.0528594) , 
54, 64.8598, 1, 0, 0.313626,-9.92114e-06) , 
9, 1.12541, 1, 0, 0.373302,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700587,0.00495191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.957712,0.0677118) , 
8, 0.147428, 1, 0, 0.918254,2.4655e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797935,0.0440452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282891,-0.0480518) , 
80, 359.136, 1, 0, 0.545903,-0.000129435) , 
24, 239.191, 1, 0, 0.835027,1.3365e+15) , 
64, 57.6918, 1, 0, 0.481103,2.06722e+18)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70118,0.0308668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445313,-0.0464858) , 
16, 2.32444, 1, 0, 0.550366,3.15976e+10) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.973161,0.0710736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.812085,0.0448405) , 
3, 39.8659, 1, 0, 0.936309,4.11904e+14) , 
14, 2.20819, 1, 0, 0.690583,0.00837688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906509,0.0712165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227491,-0.0624637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373648,-0.0010594) , 
3, 27.6832, 1, 0, 0.281823,2.62888e+19) , 
34, 113.855, 1, 0, 0.33005,0) , 
49, 12.8995, 1, 0, 0.527041,0)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20667,-0.0765044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716149,0.020366) , 
16, 2.76205, 1, 0, 0.340704,3.01382e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564694,-0.0181639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.848602,0.0472888) , 
14, 1.54657, 1, 0, 0.750278,1.43611e+08) , 
21, 35.8594, 1, 0, 0.669578,3.75121e+12) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0184328,-0.0621835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0728095,-0.0425586) , 
35, 171.157, 1, 0, 0.0314241,4.54684e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334193,0.033574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625443,-0.0463466) , 
20, 2.42474, 1, 0, 0.137376,-5.91567e-05) , 
42, 257.141, 1, 0, 0.0675032,1.16555e+19) , 
21, 75.056, 1, 0, 0.484024,780.474)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874927,0.0496756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411916,-0.0217944) , 
51, 99.3656, 1, 0, 0.790017,4.34285e+18) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459762,-0.0464299) , 
8, 1.49402, 1, 0, 0.759741,6.76028e+13) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0956386,-0.08824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601304,0.0175341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123745,-0.0402614) , 
2, 51.3045, 1, 0, 0.314753,0.0120416) , 
22, 65.3464, 1, 0, 0.269935,7.08783e+15) , 
9, 2.13825, 1, 0, 0.537133,2.21446e+18)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828266,0.0462337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28684,-0.0603056) , 
17, 2.61443, 1, 0, 0.481659,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803708,0.0131148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974088,0.0683644) , 
25, 18.5914, 1, 0, 0.944124,1.37565e+15) , 
48, 216.308, 1, 0, 0.823438,1.45628e+14) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742959,0.0724647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216632,-0.0491368) , 
12, 1.05124, 1, 0, 0.243715,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.973049,0.064774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0941449,-0.0499991) , 
21, 71.7216, 1, 0, 0.587943,2.26538e+19) , 
66, 75.2474, 1, 0, 0.32863,1.43607e+10) , 
49, 5.93542, 1, 0, 0.47955,7.42417e+13)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398753,-0.0273623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0629454,-0.109423) , 
59, 120.011, 1, 0, 0.145395,-6.04669e-05) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399269,-0.0595833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795747,0.0287368) , 
12, 0.846929, 1, 0, 0.738648,1.00016e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0601333,-0.0492502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379934,0.0399388) , 
46, 200.952, 1, 0, 0.0941231,4.25943e-09) , 
21, 72.4749, 1, 0, 0.514039,3.7524e+13) , 
21, 30.4206, 1, 0, 0.475036,2.01483e+18)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495468,-0.0447446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607228,0.00748863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964804,0.0631275) , 
79, 29.9154, 1, 0, 0.878191,2.57741e+18) , 
25, 12.626, 1, 0, 0.826313,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236548,-0.0732132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324744,-0.0198343) , 
35, 136.792, 1, 0, 0.287281,9.14337e+13) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978601,0.0605242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134557,-0.0366775) , 
21, 73.777, 1, 0, 0.644332,1.50198e+16) , 
64, 30.3023, 1, 0, 0.381923,inf) , 
56, 50.109, 1, 0, 0.498409,2.78358e+19)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.950268,0.0668861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.933972,0.0467968) , 
63, 36.1687, 1, 0, 0.944926,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423156,-0.0380349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.946628,0.0714331) , 
11, 2.26845, 1, 0, 0.584467,-5.54389e-05) , 
53, 161.487, 1, 0, 0.791673,7.42334e+18) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95925,0.0656167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513661,-0.0286046) , 
26, 64.1204, 1, 0, 0.820767,7.32064e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.919022,0.0615802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310908,-0.0415198) , 
54, 45.4931, 1, 0, 0.353483,5.37221e+14) , 
56, 46.8966, 1, 0, 0.442846,0) , 
8, 0.513732, 1, 0, 0.542337,2.91831e+19)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201281,-0.0432709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95634,0.0642559) , 
2, 37.5476, 1, 0, 0.808265,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408647,-0.0186771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183676,-0.11244) , 
4, 216.183, 1, 0, 0.390246,6.66058e+13) , 
9, 1.2302, 1, 0, 0.46705,3.0522e+19) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119759,-0.119013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656329,-0.0295188) , 
71, 198.589, 1, 0, 0.255543,2.44155e+16) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423877,0.040148) , 
9, 1.77332, 1, 0, 0.284585,inf) , 
11, 3.33007, 1, 0, 0.441958,0)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720503,-0.0201372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979278,0.0608309) , 
27, 70.0085, 1, 0, 0.952408,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0842484,-0.0404987) , 
21, 80.2092, 1, 0, 0.785782,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290686,-0.0317335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601173,0.0279594) , 
22, 99.9746, 1, 0, 0.411464,6.24417e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327823,-0.0166532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107674,-0.105973) , 
0, 5, 1, 0, 0.215941,-0.265555) , 
19, 3.02622, 1, 0, 0.369515,0) , 
49, 6.57092, 1, 0, 0.520969,0.00113269)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926624,0.0551187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284659,-0.0349073) , 
49, 45.1281, 1, 0, 0.828303,5.59044e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814972,0.0344667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305928,-0.040714) , 
56, 49.2003, 1, 0, 0.478042,1.30043e+14) , 
51, 78.6435, 1, 0, 0.627315,4.18923e+19) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119763,-0.0969522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534515,-0.0133159) , 
23, 80.631, 1, 0, 0.264762,4.67755e+11) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754687,0.0578251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0607516,-0.0377547) , 
21, 84.6852, 1, 0, 0.183717,1.81974e+16) , 
9, 1.91168, 1, 0, 0.218199,-2.28209e-05) , 
8, 1.21447, 1, 0, 0.505727,4.02266e+16)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323327,-0.0535861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394844,-0.0349931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782313,0.0412137) , 
45, 91.1329, 1, 0, 0.699852,2.81928e+08) , 
11, 0.888463, 1, 0, 0.644182,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213004,-0.123733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233846,-0.0441747) , 
9, 1.10812, 1, 0, 0.227425,1.99305e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212811,-0.0591076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452483,0.0119849) , 
52, 168.556, 1, 0, 0.406403,0) , 
3, 21.4287, 1, 0, 0.336906,1.98877e+10) , 
25, 77.6001, 1, 0, 0.489902,2.91526e+19)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917506,0.0513047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154495,-0.038895) , 
51, 109.296, 1, 0, 0.786278,2.31637e+14) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463746,-0.100018) , 
16, 3.25478, 1, 0, 0.745925,5.67323e+14) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119835,-0.0610136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493957,0.0123679) , 
48, 118.875, 1, 0, 0.445029,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446783,0.00364942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22753,-0.0688609) , 
26, 44.3313, 1, 0, 0.278812,2.65142e+19) , 
71, 187.266, 1, 0, 0.357025,-0) , 
49, 5.89599, 1, 0, 0.489175,0)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8395,0.0402363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101946,-0.0395843) , 
21, 74.4332, 1, 0, 0.705481,1.72601e+14) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313322,-0.0688563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.997709,0.0554734) , 
57, 174.724, 1, 0, 0.492961,0) , 
75, 188.82, 1, 0, 0.650144,7.95651e+08) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162945,-0.0742844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488068,0.000546223) , 
30, 151.137, 1, 0, 0.246996,2.75199e+10) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887829,0.0795282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197444,-0.0391693) , 
29, 171.924, 1, 0, 0.528234,7.19242e+11) , 
63, 33.3378, 1, 0, 0.298541,6.34495e+15) , 
54, 142.664, 1, 0, 0.497913,0)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647895,0.0121301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0987795,-0.0600493) , 
8, 1.63821, 1, 0, 0.53929,1.66705e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242265,-0.0903816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512507,-0.0132229) , 
30, 94.1028, 1, 0, 0.390789,1.26562e+14) , 
46, 196.47, 1, 0, 0.49779,337840) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144855,-0.128479) , 
14, 3.48764, 1, 0, 0.466911,5.60455e+17)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113985,-0.0910012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649444,0.0211075) , 
79, 87.9915, 1, 0, 0.223815,6.38086e+10) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918392,0.0564124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66315,0.00136722) , 
13, 2.6374, 1, 0, 0.761793,1.35105e+11) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232769,-0.0756774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376721,-0.0197789) , 
44, 105.063, 1, 0, 0.348795,1.03752e+13) , 
9, 1.88772, 1, 0, 0.541555,3.03513e+15) , 
21, 32.5629, 1, 0, 0.495737,3.5805e+18)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824765,0.0547685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445818,-0.0241551) , 
10, 3.30495, 1, 0, 0.777578,8.48847e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231834,-0.0901856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532201,-5.8924e-05) , 
12, 1.01791, 1, 0, 0.486089,1.33902e+14) , 
17, 1.84807, 1, 0, 0.576436,3.62647e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174107,-0.127274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569588,0.013319) , 
59, 134.538, 1, 0, 0.336544,0) , 
77, 268.45, 1, 0, 0.544391,0)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.121343,-0.0811952) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.077866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331462,-0.0305586) , 
54, 34.1497, 1, 0, 0.358739,5.30917e+08) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945553,0.0538543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0753524,-0.0393387) , 
21, 88.7858, 1, 0, 0.728961,7.15211e+18) , 
63, 1.44028, 1, 0, 0.452499,1.40795e+19) , 
21, 27.9422, 1, 0, 0.426299,0)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247555,-0.0766317) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95311,0.0750022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468567,-0.0110744) , 
67, 123.926, 1, 0, 0.789437,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906542,0.0663014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425772,-0.0261356) , 
12, 0.971124, 1, 0, 0.460221,1.15496e+10) , 
2, 36.7288, 1, 0, 0.504545,2.08126e+14) , 
3, 16.1402, 1, 0, 0.482061,3.54899e+18)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.861234,0.0625868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179124,-0.0241224) , 
56, 69.5398, 1, 0, 0.357745,1.68874e+15) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155166,-0.0908821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436876,0.00973205) , 
30, 116.579, 1, 0, 0.20292,0) , 
10, 2.39165, 1, 0, 0.268513,3.43571e+10) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791716,0.0369493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456604,-0.0202677) , 
78, 170.733, 1, 0, 0.701695,4.57434e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309702,-0.0712156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346976,-0.00288497) , 
59, 111.988, 1, 0, 0.338474,9.13574e+15) , 
8, 0.962788, 1, 0, 0.556319,5.16669e+16) , 
6, 33.6264, 1, 0, 0.477523,2.35142e+17)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49863,-0.026862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286291,-0.105505) , 
22, 119.016, 1, 0, 0.419031,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.953858,0.0631443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296796,-0.0462348) , 
21, 59.2922, 1, 0, 0.494765,5.05372e+18) , 
21, 49.7161, 1, 0, 0.460002,7.63407e+08) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520019,-0.0208613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904466,0.0648197) , 
12, 0.835424, 1, 0, 0.845045,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24787,-0.0146304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129619,-0.0809502) , 
65, 93.682, 1, 0, 0.230004,1.49155e+14) , 
51, 86.9138, 1, 0, 0.505671,9.30708e+16) , 
2, 55.1679, 1, 0, 0.478897,2.41318e+17)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.956276,0.067441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250919,0.00286066) , 
8, 0.994802, 1, 0, 0.634046,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358448,-0.0525346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411285,-0.00610636) , 
2, 56.8871, 1, 0, 0.378134,-7.8252e-06) , 
23, 50.7757, 1, 0, 0.406997,1.17548e+20) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8765,0.0346403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.999957,0.083707) , 
56, 48.2962, 1, 0, 0.963604,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363938,0.00759438) , 
50, 299.166, 1, 0, 0.771107,2.37901e+15) , 
58, 271.341, 1, 0, 0.450253,3.62858e+16)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781329,0.034281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290684,-0.0759966) , 
57, 128.329, 1, 0, 0.38294,5.48856e+20) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500596,0.0536062) , 
49, 27.7075, 1, 0, 0.402332,1.60577e+17) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327854,-0.0356391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747903,0.0416874) , 
21, 30.9486, 1, 0, 0.701609,3.96949e+18) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176986,-0.0693275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374771,0.00976211) , 
11, 1.73701, 1, 0, 0.288598,1.15127e+19) , 
50, 228.248, 1, 0, 0.517025,6.13017e+08) , 
33, 140.105, 1, 0, 0.488667,5.06527e+06)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267414,-0.0621501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788654,0.0502509) , 
27, 55.5871, 1, 0, 0.715272,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.891842,0.042103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328604,-0.0277537) , 
9, 1.23723, 1, 0, 0.451966,4.23376e+18) , 
37, 257.242, 1, 0, 0.530036,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272021,-0.107404) , 
62, 295.25, 1, 0, 0.51655,-0)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12711,-0.0944644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704491,0.0123115) , 
19, 1.9906, 1, 0, 0.270769,2.9894e+16) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592998,-0.00141089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864258,0.053367) , 
22, 82.7118, 1, 0, 0.741407,1.03533e+17) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307085,-0.0400489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508451,0.0258012) , 
13, 3.05608, 1, 0, 0.347299,527669) , 
24, 159.136, 1, 0, 0.49561,1.62178e+18) , 
37, 179.949, 1, 0, 0.474599,2.2135e+17)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922956,0.0451193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15552,-0.022476) , 
21, 71.799, 1, 0, 0.713179,0) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593102,-0.149982) , 
64, 141.21, 1, 0, 0.705153,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323805,-0.0149812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105813,-0.08438) , 
43, 153.62, 1, 0, 0.174197,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377226,0.0195127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137449,-0.0867754) , 
11, 3.45401, 1, 0, 0.332556,2.60286e+14) , 
38, 196.409, 1, 0, 0.257317,3.07322e+19) , 
49, 16.7636, 1, 0, 0.541223,3.28067e+19)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427267,-0.035606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146787,-0.13159) , 
36, 360.642, 1, 0, 0.273807,2.1551e+15) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768879,0.0400909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142618,-0.0806803) , 
49, 13.5202, 1, 0, 0.529157,1.92366e+16) , 
3, 21.6863, 1, 0, 0.402617,1.33762e+19) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294432,-0.0916921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60006,0.0267706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206576,-0.0512033) , 
69, 408.46, 1, 0, 0.529223,-8.82046e-06) , 
39, 144.157, 1, 0, 0.515447,1.72266e-09) , 
26, 19.4622, 1, 0, 0.485632,0)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475067,-0.0250181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91756,0.0516522) , 
7, 48.3142, 1, 0, 0.767075,1.67494e+19) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.894106,0.0905959) , 
49, 24.9292, 1, 0, 0.780258,1.19851e+15) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399847,-0.0309066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231296,-0.115779) , 
11, 3.31088, 1, 0, 0.382669,-1.27146e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.970945,0.0602101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100032,-0.0230862) , 
21, 71.4134, 1, 0, 0.482019,0) , 
55, 149.026, 1, 0, 0.415889,0) , 
50, 160.972, 1, 0, 0.505513,0)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442286,-0.0511372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984178,0.0593558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0493893,-0.0361103) , 
21, 78.9796, 1, 0, 0.737433,7.68366e+15) , 
11, 0.995084, 1, 0, 0.69469,0) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556813,0.0473085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342482,-0.0480348) , 
30, 61.5976, 1, 0, 0.375087,0) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715344,0.0664419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248862,-0.0188011) , 
56, 93.9678, 1, 0, 0.432087,3.65856e+18) , 
2, 66.1629, 1, 0, 0.392232,3.80533e+18) , 
49, 8.02818, 1, 0, 0.532301,3.40242e+13)    );
   return;
};

// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
