// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : jbhyun
Date           : Fri Jan  8 20:48:15 2021
Host           : Linux SFT-ubuntu-1804-3 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jbhyun/Forge/BDTTrain/tmva
Training events: 38314
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "30" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "6" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 39
Nj                            Nj                            Nj                            Nj                                                              'I'    [3,12]
Nb                            Nb                            Nb                            Nb                                                              'I'    [1,5]
Ptl1                          Ptl1                          Ptl1                          Ptl1                                                            'F'    [20.0038032532,3528.63354492]
Ptl2                          Ptl2                          Ptl2                          Ptl2                                                            'F'    [10.0008687973,180.782180786]
Ptj1                          Ptj1                          Ptj1                          Ptj1                                                            'F'    [26.307554245,1258.36206055]
Ptj2                          Ptj2                          Ptj2                          Ptj2                                                            'F'    [25.1116371155,736.982543945]
Ptj3                          Ptj3                          Ptj3                          Ptj3                                                            'F'    [25.0010318756,522.453979492]
Ptb1                          Ptb1                          Ptb1                          Ptb1                                                            'F'    [25.0105686188,1143.94543457]
Ptb2                          Ptb2                          Ptb2                          Ptb2                                                            'F'    [-1,655.882995605]
MET                           MET                           MET                           MET                                                             'F'    [0.282745182514,640.504699707]
dEtall                        dEtall                        dEtall                        dEtall                                                          'F'    [3.77297401428e-05,4.61115884781]
dRll                          dRll                          dRll                          dRll                                                            'F'    [0.0932734832168,5.40484428406]
dRjj12                        dRjj12                        dRjj12                        dRjj12                                                          'F'    [0.394186288118,5.51146507263]
dRjj23                        dRjj23                        dRjj23                        dRjj23                                                          'F'    [0.401400059462,5.38182353973]
dRjj13                        dRjj13                        dRjj13                        dRjj13                                                          'F'    [0.407925158739,5.51293802261]
dRlj11                        dRlj11                        dRlj11                        dRlj11                                                          'F'    [0.400195807219,5.56941890717]
dRlj12                        dRlj12                        dRlj12                        dRlj12                                                          'F'    [0.400101214647,5.62248182297]
dRlj13                        dRlj13                        dRlj13                        dRlj13                                                          'F'    [0.400550603867,5.40495634079]
dRlj21                        dRlj21                        dRlj21                        dRlj21                                                          'F'    [0.400000184774,5.42530488968]
dRlj22                        dRlj22                        dRlj22                        dRlj22                                                          'F'    [0.400301247835,5.37719631195]
dRlj23                        dRlj23                        dRlj23                        dRlj23                                                          'F'    [0.400580734015,5.38203430176]
dRlb11                        dRlb11                        dRlb11                        dRlb11                                                          'F'    [0.400195807219,5.26424264908]
dRlb21                        dRlb21                        dRlb21                        dRlb21                                                          'F'    [0.400000184774,5.4061126709]
MSSSF                         MSSSF                         MSSSF                         MSSSF                                                           'F'    [4.02011299133,586.325866699]
Mbl11                         Mbl11                         Mbl11                         Mbl11                                                           'F'    [13.8539085388,1656.56530762]
Mbl12                         Mbl12                         Mbl12                         Mbl12                                                           'F'    [9.86602306366,906.669189453]
Mllb1                         Mllb1                         Mllb1                         Mllb1                                                           'F'    [23.5393028259,1693.21569824]
Mllb2                         Mllb2                         Mllb2                         Mllb2                                                           'F'    [-1,716.596130371]
MTvl1                         MTvl1                         MTvl1                         MTvl1                                                           'F'    [8.4366016381e-05,812.348022461]
MTvl2                         MTvl2                         MTvl2                         MTvl2                                                           'F'    [0.0061067705974,531.094665527]
MTvll                         MTvll                         MTvll                         MTvll                                                           'F'    [0.00208275602199,898.194091797]
HT                            HT                            HT                            HT                                                              'F'    [77.2579269409,2294.91650391]
MET2HT                        MET2HT                        MET2HT                        MET2HT                                                          'F'    [0.000300817482639,1696.20458984]
MllW_2j                       MllW_2j                       MllW_2j                       MllW_2j                                                         'F'    [59.8283576965,1385.69995117]
MllW_1j                       MllW_1j                       MllW_1j                       MllW_1j                                                         'F'    [8.04352283478,586.325866699]
Ml1W_2jL                      Ml1W_2jL                      Ml1W_2jL                      Ml1W_2jL                                                        'F'    [27.726234436,1370.94238281]
Ml1W_1jL                      Ml1W_1jL                      Ml1W_1jL                      Ml1W_1jL                                                        'F'    [11.8492107391,1656.56530762]
Ml2W_2jL                      Ml2W_2jL                      Ml2W_2jL                      Ml2W_2jL                                                        'F'    [21.1876487732,1175.76672363]
Ml2W_1jL                      Ml2W_1jL                      Ml2W_1jL                      Ml2W_1jL                                                        'F'    [8.59082317352,1021.68920898]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 39 )
   {
      // the training input variables
      const char* inputVars[] = { "Nj", "Nb", "Ptl1", "Ptl2", "Ptj1", "Ptj2", "Ptj3", "Ptb1", "Ptb2", "MET", "dEtall", "dRll", "dRjj12", "dRjj23", "dRjj13", "dRlj11", "dRlj12", "dRlj13", "dRlj21", "dRlj22", "dRlj23", "dRlb11", "dRlb21", "MSSSF", "Mbl11", "Mbl12", "Mllb1", "Mllb2", "MTvl1", "MTvl2", "MTvll", "HT", "MET2HT", "MllW_2j", "MllW_1j", "Ml1W_2jL", "Ml1W_1jL", "Ml2W_2jL", "Ml2W_1jL" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[39];
   double fVmax[39];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[39];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.550102091761678);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 20.1463, 0, 1, 0.696691,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25688,-99) , 
3, 21.6997, 0, 0, 0.347069,-99) , 
32, 20.1074, 1, 0, 0.596328,-99) , 
NN(
0, 
0, 
-1, 96.0356, 0, -1, 0.0576405,-99) , 
23, 73.205, 1, 0, 0.490057,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.503516);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 11.6743, 0, 1, 0.801101,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319698,-99) , 
3, 16.7734, 0, 0, 0.460245,-99) , 
1, 2, 0, 0, 0.568349,-99) , 
NN(
0, 
0, 
-1, 0.882975, 1, -1, 0.103733,-99) , 
23, 72.4936, 1, 0, 0.492962,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.391148);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.848091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488786,-99) , 
3, 12.685, 0, 0, 0.765367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287713,-99) , 
9, 60.3926, 1, 0, 0.42728,-99) , 
27, 69.1212, 0, 0, 0.519885,-99) , 
NN(
0, 
0, 
-1, 24.1803, 0, -1, 0.0785712,-99) , 
23, 78.1412, 1, 0, 0.464708,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.397187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 20.5736, 1, 1, 0.73003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260936,-99) , 
10, 1.85074, 1, 0, 0.679798,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341568,-99) , 
32, 7.67393, 1, 0, 0.430029,-99) , 
NN(
0, 
0, 
-1, 2.04663, 1, -1, 0.136152,-99) , 
23, 68.3344, 1, 0, 0.368827,-99) , 
27, 70.0491, 0, 0, 0.450269,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.344394);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 55.8393, 0, 1, 0.827355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429081,-99) , 
38, 29.8289, 1, 0, 0.487245,-99) , 
3, 26.9134, 0, 0, 0.539217,-99) , 
NN(
0, 
0, 
-1, 24.3058, 0, -1, 0.148139,-99) , 
23, 73.323, 1, 0, 0.484763,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.304435);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 6.7026, 1, 1, 0.594698,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.149817,-99) , 
2, 53.6053, 0, 0, 0.254696,-99) , 
23, 24.8469, 0, 0, 0.55798,-99) , 
NN(
0, 
0, 
-1, 24.1851, 0, -1, 0.175498,-99) , 
23, 71.5037, 1, 0, 0.496506,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.249907);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 15.3519, 1, 1, 0.856666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305517,-99) , 
32, 24.5402, 1, 0, 0.468088,-99) , 
3, 31.9623, 0, 0, 0.500973,-99) , 
NN(
0, 
0, 
-1, 24.2693, 0, -1, 0.130026,-99) , 
23, 77.9449, 1, 0, 0.459933,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.331001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.773671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482004,-99) , 
32, 15.3476, 1, 0, 0.665873,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384243,-99) , 
27, 103.154, 0, 0, 0.428794,-99) , 
3, 20.0239, 0, 0, 0.505446,-99) , 
NN(
0, 
0, 
-1, 24.2658, 0, -1, 0.168027,-99) , 
23, 79.1149, 1, 0, 0.469419,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.303584);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.783921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436991,-99) , 
23, 29.0038, 0, 0, 0.739362,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427161,-99) , 
0, 5, 0, 0, 0.484283,-99) , 
27, 90.1576, 0, 0, 0.54155,-99) , 
NN(
0, 
0, 
-1, 24.698, 0, -1, 0.212312,-99) , 
23, 73.225, 1, 0, 0.496194,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.2799);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.713929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382313,-99) , 
32, 47.0536, 1, 0, 0.671494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425616,-99) , 
27, 79.3673, 0, 0, 0.472654,-99) , 
21, 2.61568, 0, 0, 0.523491,-99) , 
NN(
0, 
0, 
-1, 2.27885, 1, -1, 0.183579,-99) , 
10, 1.87193, 1, 0, 0.48789,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.212662);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4, 0, 1, 0.839105,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462148,-99) , 
38, 26.0709, 1, 0, 0.500112,-99) , 
3, 33.6481, 0, 0, 0.523925,-99) , 
NN(
0, 
0, 
-1, 22.6114, 0, -1, 0.256722,-99) , 
23, 72.6646, 1, 0, 0.488449,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.197348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 35.3644, 0, 1, 0.562456,-99) , 
NN(
0, 
0, 
-1, 43.1521, 1, -1, 0.274035,-99) , 
23, 25.2334, 0, 0, 0.532566,-99) , 
NN(
0, 
0, 
-1, 23.8141, 0, -1, 0.236507,-99) , 
23, 77.9449, 1, 0, 0.503598,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.200348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 73.7025, 1, 1, 0.724622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458416,-99) , 
8, 25.2564, 0, 0, 0.496898,-99) , 
3, 30.2951, 0, 0, 0.526048,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507667,-99) , 
NN(
0, 
0, 
-1, 71.1244, 1, -1, 0.212996,-99) , 
8, 31.4197, 0, 0, 0.267578,-99) , 
10, 1.73786, 1, 0, 0.494291,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.154634);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.70747, 1, 1, 0.706455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.757482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483303,-99) , 
38, 127.773, 0, 0, 0.50149,-99) , 
27, 111.194, 0, 0, 0.531401,-99) , 
NN(
0, 
0, 
-1, 2.40171, 1, -1, 0.253569,-99) , 
10, 1.87193, 1, 0, 0.503858,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.215578);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.70376, 1, 1, 0.742836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445592,-99) , 
32, 15.3488, 1, 0, 0.527727,-99) , 
24, 165.565, 0, 0, 0.55409,-99) , 
NN(
0, 
0, 
-1, 70.0815, 1, -1, 0.247668,-99) , 
10, 1.91759, 1, 0, 0.526319,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.251584);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.21074, 1, 1, 0.592291,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371486,-99) , 
2, 60.0096, 0, 0, 0.439253,-99) , 
23, 34.4585, 0, 0, 0.553173,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.766256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445314,-99) , 
11, 1.59545, 1, 0, 0.518154,-99) , 
NN(
0, 
0, 
-1, 2.75483, 0, -1, 0.245161,-99) , 
3, 23.206, 0, 0, 0.362806,-99) , 
23, 64.2817, 1, 0, 0.511494,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.147874);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 47.5917, 0, 1, 0.849503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273548,-99) , 
23, 22.4281, 0, 0, 0.508992,-99) , 
30, 158.032, 0, 0, 0.52587,-99) , 
NN(
0, 
0, 
-1, 22.6114, 0, -1, 0.292743,-99) , 
23, 78.0603, 1, 0, 0.502168,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.211969);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2, 0, 1, 0.668518,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.859963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481473,-99) , 
38, 149.792, 0, 0, 0.500022,-99) , 
0, 5, 0, 0, 0.549175,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.708184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438515,-99) , 
5, 67.7007, 1, 0, 0.556587,-99) , 
NN(
0, 
0, 
-1, 53.2843, 0, -1, 0.327326,-99) , 
9, 26.868, 1, 0, 0.361426,-99) , 
10, 1.17313, 1, 0, 0.487057,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.186943);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 45.6078, 0, 1, 0.569893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308209,-99) , 
23, 21.7748, 0, 0, 0.547909,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328834,-99) , 
28, 67.6674, 1, 0, 0.430983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.194279,-99) , 
12, 1.35863, 0, 0, 0.399874,-99) , 
11, 2.34105, 1, 0, 0.497831,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.22982);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 32.0116, 0, 1, 0.768924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35966,-99) , 
38, 44.425, 1, 0, 0.473746,-99) , 
23, 33.9835, 0, 0, 0.608735,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395205,-99) , 
34, 86.4716, 1, 0, 0.476693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29668,-99) , 
18, 1.47518, 1, 0, 0.334012,-99) , 
3, 13.1487, 0, 0, 0.433672,-99) , 
11, 1.37046, 1, 0, 0.476587,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.168802);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 89.4807, 1, 1, 0.72668,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419052,-99) , 
0, 4, 0, 0, 0.490235,-99) , 
NN(
0, 
0, 
-1, 57.9086, 1, -1, 0.303387,-99) , 
10, 1.73492, 1, 0, 0.466317,-99) , 
30, 131.119, 0, 0, 0.488181,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.191902);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.64612, 0, 1, 0.659219,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444418,-99) , 
3, 43.7826, 0, 0, 0.457004,-99) , 
NN(
0, 
0, 
-1, 29.104, 0, -1, 0.289914,-99) , 
10, 1.73493, 1, 0, 0.433645,-99) , 
38, 28.3175, 1, 0, 0.467038,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.17431);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.33093, 1, 1, 0.754162,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416341,-99) , 
23, 66.9933, 1, 0, 0.529391,-99) , 
NN(
0, 
0, 
-1, 139.658, 1, -1, 0.317018,-99) , 
9, 95.0885, 1, 0, 0.498668,-99) , 
30, 149.648, 0, 0, 0.512646,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.190384);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.812369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461812,-99) , 
10, 0.172275, 0, 0, 0.741286,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.833764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481804,-99) , 
24, 171.018, 0, 0, 0.511582,-99) , 
27, 55.8393, 0, 0, 0.567474,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694517,-99) , 
NN(
0, 
0, 
-1, 67.4028, 1, -1, 0.413297,-99) , 
18, 0.783764, 1, 0, 0.427824,-99) , 
3, 17.7408, 0, 0, 0.487519,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.187842);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 14.375, 0, 1, 0.773178,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393538,-99) , 
14, 2.36408, 1, 0, 0.45488,-99) , 
9, 83.2196, 1, 0, 0.670601,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399585,-99) , 
9, 94.573, 1, 0, 0.612101,-99) , 
NN(
0, 
0, 
-1, 1.27917, 1, -1, 0.441738,-99) , 
27, 65.9727, 0, 0, 0.476592,-99) , 
24, 163.363, 0, 0, 0.501653,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.148793);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 61.4282, 1, 1, 0.654101,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.751054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482994,-99) , 
30, 125.51, 0, 0, 0.502811,-99) , 
NN(
0, 
0, 
-1, 65.3936, 1, -1, 0.29611,-99) , 
23, 68.2982, 1, 0, 0.480276,-99) , 
3, 23.9362, 0, 0, 0.516406,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.15049);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.59206, 1, 1, 0.716638,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480077,-99) , 
32, 10.3863, 1, 0, 0.541947,-99) , 
NN(
0, 
0, 
-1, 163.613, 1, -1, 0.430065,-99) , 
21, 1.53091, 0, 0, 0.506727,-99) , 
30, 138.106, 0, 0, 0.521413,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.176003);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 40.0424, 1, 1, 0.621906,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490945,-99) , 
28, 42.2649, 1, 0, 0.53281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.252358,-99) , 
23, 69.8815, 1, 0, 0.509481,-99) , 
3, 18.4554, 0, 0, 0.556122,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.124465);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.29594, 1, 1, 0.742697,-99) , 
NN(
NN(
0, 
0, 
-1, 247.067, 0, 1, 0.662407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466021,-99) , 
30, 46.4161, 1, 0, 0.498708,-99) , 
38, 22.0319, 1, 0, 0.512812,-99) , 
30, 151.198, 0, 0, 0.524097,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0651022);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809814,-99) , 
NN(
NN(
0, 
0, 
-1, 149.729, 0, 1, 0.515091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268574,-99) , 
10, 2.24959, 1, 0, 0.504306,-99) , 
36, 25.9409, 1, 0, 0.51282,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
